spring:
  application:
    name: auth

  datasource:
    driver-class-name: ${DATABASE_DRIVER_CLASS_NAME}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

#  mail:
#    host: ${MAIL_HOST}
#    port: ${MAIL_PORT}
#    username: ${MAIL_USERNAME}
#    password: ${MAIL_PASSWORD}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

server:
  port: 8001

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

frontend:
  url: ${FRONTEND_URL}

sendgrid:
  api:
    key: ${MAIL_API_KEY}

app:
  mail:
    from: ${MAIL_FROM}
